### ISSUE TITLE
spaces not tabs

### ISSUE THREAD

**Issue by rainiera** [txconvergent/oss-demo#1]
[PEP 8](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces)

**Comment by dilptl23** [comment]
Once you start with tabs, you never go back

**Comment by rainiera** [comment]
[Tabs versus Spaces, _Silicon Valley S03E06_](https://www.youtube.com/watch?v=SsoOG6ZeyUI)

**Comment by dilptl23** [comment]
That is exactly what I was thinking of when you posted

**Comment by jshph** [comment]
`git blame original repo author`...
I just modified one line of code O_O
But thanks for reminding me to update my new machine's Sublime settings to spaces :P
